site_name: Open Park Project Docs
theme:
  name: material

nav:
  - Client:
      - Features: features.md
      - Superuser Guide: superuser.md
      - Admin Guide: admin.md
      - Controller Guide: controller.md
      - Driver Guide: driver.md
      - Visitor Guide: visitor.md
