site_name: Open Park Project Documentation
theme:
  name: material
  language: en

plugins:
  - openapi_markdown:
      enabled: true
      openapi_file: openapi.yaml
      output_file: api_doc.md

nav:
  - Home: index.md
  - APIs: api_doc.md
  - App Usage:
      - Features: features.md
      - Login & Registration: login_register.md
      - Driver Guide: driver.md
      - Controller Guide: controller.md
      - Admin Guide: admin.md
      - Totem Guide: totem.md
      - Getting Started: getting_started.md
      - FAQ: faq.md
