name: Deploy Docs

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: 
      - OPP-common-updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin mkdocs-build-plantuml-plugin

      - name: Get OpenAPI spec
        run: |
          curl -o docs/openapi.yaml https://raw.githubusercontent.com/OpenParkProject/OPP-common/refs/heads/main/openapi.yaml
      
      - name: Build and Deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
